export const ADD_DRONE_INFO = 'ADD_DRONE_INFO'
export const UPDATE_DRONE_INFO = 'UPDATE_DRONE_INFO'
export const REMOVE_DRONE_INFO = 'REMOVE_DRONE_INFO'

export const ADD_HIVE_INFO = 'ADD_HIVE_INFO'
export const UPDATE_HIVE_INFO = 'UPDATE_HIVE_INFO'
export const REMOVE_HIVE_INFO = 'REMOVE_HIVE_INFO'

export const CHANGE_INFO = 'CHANGE_INFO'
