export const ADD_DRONES = 'ADD_DRONES'
export const UPDATE_DRONE = 'UPDATE_DRONE'
export const REMOVE_DRONE = 'REMOVE_DRONE'

export const ADD_HIVES = 'ADD_HIVES'
export const UPDATE_HIVE = 'UPDATE_HIVE'
export const REMOVE_HIVE = 'REMOVE_HIVE'

export const CHANGE_SIDEBAR_INFO = 'CHANGE_SIDEBAR_INFO'
export const SELECT_DRONE = 'SELECT_DRONE'
