subscription onDroneAdded {
	droneAdded {
		id
		route {
			from {
				longitude
				latitude
			}
			to {
				longitude
				latitude
			}
			currentPosition {
				longitude
				latitude
			}
		}
	}
}
