query all_drones_and_hives {
	hives {
		id
		location
		coordinates {
			longitude
			latitude
		}
	}
	drones {
		id
		route {
			from {
				longitude
				latitude
			}
			to {
				longitude
				latitude
			}
			currentPosition {
				longitude
				latitude
			}
		}
	}
}
