query hives_shops {
  hives {
    id
    location {
      address
      longitude
      latitude
    }
    type {
      __typename
      ... on Hive {
        id
        name
		demand
      }
    }
  },
  shops {
    id
    location {
      address
      longitude
      latitude
    }
    type {
      __typename
      ... on Shop {
        id
        name
      }
    }
  }
}
