query ($routeId: ID!) {
	orderFromRoute(routeId: $routeId) {
		id
		shop {
			id
    		type {
      			__typename
      			... on Shop {
        			id
        			name
      			}
    		}
		}
		customer {
			id
    		location {
				address
			}
		}
		route
		source
	}
}
