{
  routes {
    id
    hops {
      id
      start {
        id
        location {
          address
          longitude
          latitude
        }
        type {
          __typename
          ... on Hive {
            id
            name
          }
        }
      }
      end {
        id
        location {
          address
          longitude
          latitude
        }
        type {
          __typename
          ... on Hive {
            id
            name
          }
        }
      }
    }
  }
}
